### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NicoTine34** [segabl/pd2-kill-feed#11]
I got this crash sometimes when im playing on hoxton breakout day 2

Application has crashed: C++ exception
mods/KillFeed/killfeed.lua:225: attempt to index a nil value

SCRIPT STACK

add_kill() @mods/KillFeed/killfeed.lua:300
_on_damage_received() @mods/KillFeed/killfeed.lua:383
sync_damage_explosion() lib/units/enemies/cop/copdamage.lua:2361
lib/network/handlers/unitnetworkhandler.lua:348

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by segabl** [comment]
When exactly did that happen?

**Comment by NicoTine34** [comment]
when i killed the captain winters i go back to Hoxton and my game crash instantly I was hosting the game.

**Comment by segabl** [comment]
I will put out a larger update today, please let me know if it still happens after that.

**Comment by NicoTine34** [comment]
Alright thanks you !

**Comment by NicoTine34** [comment]
i got crash playing 5 minutes heist

Application has crashed: C++ exception
mods/HopLib/req/UnitInfoManager.lua:65: attempt to perform arithmetic on field '_damage' (a nil value)



SCRIPT STACK

_call_listeners() @mods/HopLib/lua/copdamage.lua:6
_on_damage_received() lib/units/enemies/cop/copdamage.lua:2832
stun_hit() lib/units/enemies/cop/copdamage.lua:1324
detect_and_stun() lib/managers/explosionmanager.lua:188
_detonate() lib/units/weapons/grenades/concussiongrenade.lua:68
lib/units/weapons/grenades/grenadebase.lua:28

**Comment by segabl** [comment]
Thanks for the report, this should be fixed now
