### ISSUE TITLE
Action fail

### ISSUE THREAD

**Issue by xanaguy** [segabl/pd2-kill-feed#12]
https://imgur.com/a/2VFup  

Possible string error.

**Comment by segabl** [comment]
Hmm this is weird, when did this start happening? I works fine on my end, could you check the loc directory and see if the english.txt contains those entries? Also is this happening to every text, like in the menu too?

**Comment by xanaguy** [comment]
It immediately stopped when I updated your HopLib... Most strange. I guess this is fixed now. And when it started? I cant say for sure. I think it was after I was on a previous version earlier today.

**Comment by segabl** [comment]
Well that's good to hear, still very weird. If it happens again, reopen.
