### ISSUE TITLE
Keeper Joker Names somehow incompatible with Killfeed

### ISSUE THREAD

**Issue by xanaguy** [segabl/pd2-kill-feed#13]
When a joker of mine scores a kill or even an assist, their names are not displayed on the Killfeed. It will only display the unit type in white.

**Comment by segabl** [comment]
What did you set the name format to? And do you have show Joker names enabled in Keepers?

**Comment by xanaguy** [comment]
My name format was: "%K: %N (%T)" And my Joker's name has been shown at all times.

**Comment by segabl** [comment]
Hm that's weird, it works fine for me. I'll see if I can find out why it happens.

**Comment by xanaguy** [comment]
https://imgur.com/a/cZehM - This was after I shortened the naming format. Killfeed on the right displays the issue.

**Comment by xanaguy** [comment]
Issue found and resolved: Thanks again!
