### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NicoTine34** [segabl/pd2-kill-feed#15]
I got this crash randomly during a heist, Maybe incompatible with Pocohud ?

Application has crashed: C++ exception
mods/KillFeed/killfeed.lua:71: attempt to concatenate local 'attacker_name' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
add_kill() @mods/KillFeed/killfeed.lua:228
func() @mods/KillFeed/killfeed.lua:293
Call() @mods/base/req/core/Hooks.lua:109
_call_listeners() @mods/HopLib/lua/copdamage.lua:7
Run() lib/units/enemies/cop/copdamage.lua:2849
_on_damage_received() @mods/PocoHud3/poco/../poco/Hud3.lua:2340
sync_damage_fire() lib/units/enemies/cop/copdamage.lua:2540
lib/network/handlers/unitnetworkhandler.lua:376

**Comment by segabl** [comment]
I don't think it's caused by PocoHUD, something went wrong with trying to display the attacker name. I will look into it as soon as I got time.

**Comment by segabl** [comment]
Is this still happening for you?
