### ISSUE TITLE
Error after update.

### ISSUE THREAD

**Issue by Andreybest** [segabl/pd2-kill-feed#3]
Got this error.
Application has crashed: C++ exception
mods/KillFeed/killfeed.lua:398: bad argument #1 to 'pairs' (table expected, got boolean)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                      aswhookx  (???)     ???                                                 

-------------------------------

**Comment by Andreybest** [comment]
I think i found problem. For some reasons in mod floder after update there are 2 folders. Killfeed and pd2-kill-feed-master . After deleting "pd2-kill-feed-master" everything works fine.

**Comment by segabl** [comment]
Hmm, did you download the mod from github before?

**Comment by Andreybest** [comment]
nope
only from modworkshop site

**Comment by segabl** [comment]
Hmm, the fact that you had a folder named "pd2-kill-feed-master" suggests that it was downloaded from GitHub, Don't know how this could happen without you actively downloading it from here. I'll close this one, if it happens again, feel free to re-open it with additional information.
