### ISSUE TITLE
Quality of Life(?) Additions. 

### ISSUE THREAD

**Issue by xanaguy** [segabl/pd2-kill-feed#7]
While Kill Feed is a fantastic mod, I do feel as though there are some things that can be added to greatly improve. For example: If a cloaker kicks a player, the feed should display "Cloaker kicked (playername)" in text mode, and/or "Bulldozer and FBI Heavy SWAT downed (playername)" which will quickly identify any threat that's near the downed player so the rescuing player(s) can be on extra guard.

**Comment by segabl** [comment]
Yes this was originally planned when I started the mod, however it is quite difficult, if not impossible to implement because player damage is handled locally by every client. However, I will have another look at it soon and see if there's some way the reasons for being downed are synced.
